### ISSUE TITLE
[meta] Hardening

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-CMS-API#40]
- [x] https
- [x] salt/encrypt siteId, access token - NO?
- [x] encrypt data at rest: plugins, accounts, url of website
- [x] ensure that module/plugin file is read-only
- [x] document; Internal FAQ: What happens if someone changes the target of the file
- [x] research: multi-factor authentication in an application, challenge/response on a multi-factor authentication, ssh keys, how passpack works
- [x] store: creation date, vs updated date for the module file

to hack into system:
1. issue new credential
2. cred that is generated has target location embedded

do we require 2-fa authentication to update data on govready server

**Comment by jlyon** [comment]
At bottom of screen "This plugin is communicating with x address" (whether it is plugin.govready,com) or not

**Comment by jlyon** [comment]
Message at the bottom of the page was added by Alex.
